"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'portfolio',
]

UNFOLD = {
    'SITE_TITLE': 'm0r64n4 admin',
    'SITE_HEADER': 'm0r64n4',
    'SITE_SUBHEADER': 'Управление сайтом и заявками',
    'SITE_URL': '/',
    'SITE_SYMBOL': 'code_blocks',
    'STYLES': [
        lambda request: static('portfolio/css/admin.css'),
    ],
    'SCRIPTS': [
        lambda request: static('portfolio/js/admin-pwa.js'),
    ],
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': _('Контент сайта'),
                'separator': True,
                'items': [
                    {
                        'title': _('Настройки сайта'),
                        'icon': 'settings',
                        'link': reverse_lazy('admin:portfolio_sitesettings_changelist'),
                    },
                    {
                        'title': _('Секции страницы'),
                        'icon': 'view_quilt',
                        'link': reverse_lazy('admin:portfolio_pagesection_changelist'),
                    },
                    {
                        'title': _('Текстовые блоки'),
                        'icon': 'article',
                        'link': reverse_lazy('admin:portfolio_textblock_changelist'),
                    },
                    {
                        'title': _('Опыт и образование'),
                        'icon': 'timeline',
                        'link': reverse_lazy('admin:portfolio_timelineitem_changelist'),
                    },
                    {
                        'title': _('Технологии'),
                        'icon': 'terminal',
                        'link': reverse_lazy('admin:portfolio_technology_changelist'),
                    },
                ],
            },
            {
                'title': _('Портфолио'),
                'separator': True,
                'items': [
                    {
                        'title': _('Проекты'),
                        'icon': 'work',
                        'link': reverse_lazy('admin:portfolio_project_changelist'),
                    },
                    {
                        'title': _('Шаблоны'),
                        'icon': 'dashboard_customize',
                        'link': reverse_lazy('admin:portfolio_templatedemo_changelist'),
                    },
                    {
                        'title': _('Сертификаты'),
                        'icon': 'workspace_premium',
                        'link': reverse_lazy('admin:portfolio_certificate_changelist'),
                    },
                    {
                        'title': _('Документы для клиентов'),
                        'icon': 'folder_open',
                        'link': reverse_lazy('admin:portfolio_clientdocument_changelist'),
                    },
                ],
            },
            {
                'title': _('Заявки и оплата'),
                'separator': True,
                'items': [
                    {
                        'title': _('Заявки на проекты'),
                        'icon': 'mail',
                        'link': reverse_lazy('admin:portfolio_projectorder_changelist'),
                    },
                    {
                        'title': _('Типы проектов'),
                        'icon': 'category',
                        'link': reverse_lazy('admin:portfolio_orderprojecttype_changelist'),
                    },
                    {
                        'title': _('Сроки'),
                        'icon': 'schedule',
                        'link': reverse_lazy('admin:portfolio_orderdeadline_changelist'),
                    },
                    {
                        'title': _('Условия работы'),
                        'icon': 'fact_check',
                        'link': reverse_lazy('admin:portfolio_orderworkterm_changelist'),
                    },
                    {
                        'title': _('Оплата'),
                        'icon': 'payments',
                        'link': reverse_lazy('admin:portfolio_orderpaymentsettings_changelist'),
                    },
                    {
                        'title': _('Подтверждения оплат'),
                        'icon': 'receipt_long',
                        'link': reverse_lazy('admin:portfolio_paymentconfirmation_changelist'),
                    },
                ],
            },
            {
                'title': _('Служебное'),
                'separator': True,
                'items': [
                    {
                        'title': _('Юридическая информация'),
                        'icon': 'gavel',
                        'link': reverse_lazy('admin:portfolio_legaldocument_changelist'),
                    },
                    {
                        'title': _('Пользователи'),
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / 'staticfiles'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ORDER_EMAIL_TO = os.getenv('ORDER_EMAIL_TO', EMAIL_HOST_USER)
