from django.urls import path
from .views import (
    home,
    project_detail,
    robots_txt,
    sitemap_xml,
    manifest_json,
    admin_manifest_json,
    admin_apple_touch_icon,
    service_worker_js,
    offline_page,
    template_demo_list,
    template_demo_detail,
    project_order,
    project_order_success,
    legal_document,
    payment_page,
    payment_success,
    client_documents,
)

urlpatterns = [
    path('', home, name='home'),
    path('projects/<slug:slug>/', project_detail, name='project_detail'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap_xml, name='sitemap_xml'),
    path('manifest.json', manifest_json, name='manifest_json'),
    path('admin-manifest.json', admin_manifest_json, name='admin_manifest_json'),
    path('admin-apple-touch-icon.png', admin_apple_touch_icon, name='admin_apple_touch_icon'),
    path('service-worker.js', service_worker_js, name='service_worker_js'),
    path('offline/', offline_page, name='offline_page'),
    path('templates/', template_demo_list, name='template_demo_list'),
    path('templates/<slug:slug>/', template_demo_detail, name='template_demo_detail'),
    path('order/', project_order, name='project_order'),
    path('order/success/', project_order_success, name='project_order_success'),
    path('legal/<slug:slug>/', legal_document, name='legal_document'),
    path('payment/', payment_page, name='payment_page'),
    path('payment/success/', payment_success, name='payment_success'),
    path('client-documents/', client_documents, name='client_documents'),
]