# Generated by Django 6.0.5 on 2026-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название сертификата')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Организация')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Файл сертификата')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('stack', models.CharField(max_length=255, verbose_name='Стек технологий')),
                ('github_url', models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Ссылка на демо')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Обложка проекта')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('about', models.TextField(verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Резюме')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
