# Generated by Django 6.0.5 on 2026-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_textblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='Завершён', max_length=50, verbose_name='Статус проекта'),
        ),
    ]
