# Generated by Django 6.0.5 on 2026-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_sitesettings_about_project_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('experience', 'Опыт'), ('education', 'Образование')], max_length=20, verbose_name='Категория')),
                ('period', models.CharField(max_length=100, verbose_name='Период')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Опыт / образование',
                'verbose_name_plural': 'Опыт и образование',
                'ordering': ['order', 'id'],
            },
        ),
    ]
