# Generated by Django 6.0.5 on 2026-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_timelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название сайта во вкладке'),
        ),
    ]
