# Generated by Django 6.0.5 on 2026-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_sitesettings_favicon_sitesettings_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Показывать в меню'),
        ),
    ]
