# Generated by Django 6.0.5 on 2026-06-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_pagesection_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='URL-адрес проекта'),
        ),
    ]
