# Generated by Django 6.0.5 on 2026-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для превью ссылки'),
        ),
    ]
