# Generated by Django 6.0.5 on 2026-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_sitesettings_og_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL-адрес')),
                ('category', models.CharField(choices=[('ui', 'UI-компоненты'), ('animation', 'Анимации'), ('carousel', 'Карусели'), ('form', 'Формы'), ('auth', 'Авторизация'), ('other', 'Другое')], default='ui', max_length=30, verbose_name='Категория')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='template_demos/', verbose_name='Обложка')),
                ('html_code', models.TextField(blank=True, verbose_name='HTML')),
                ('css_code', models.TextField(blank=True, verbose_name='CSS')),
                ('js_code', models.TextField(blank=True, verbose_name='JavaScript')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Демо-ссылка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['order', 'title'],
            },
        ),
    ]
