# Generated by Django 6.0.5 on 2026-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_templatedemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedemo',
            name='difficulty',
            field=models.CharField(default='Средняя', max_length=30, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='templatedemo',
            name='features',
            field=models.CharField(blank=True, max_length=255, verbose_name='Что использует'),
        ),
    ]
