# Generated by Django 6.0.5 on 2026-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_templatedemo_difficulty_templatedemo_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL-адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'категория применения',
                'verbose_name_plural': 'Для чего подходит',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='templatedemo',
            name='use_cases',
            field=models.ManyToManyField(blank=True, related_name='templates', to='portfolio.templateusecase', verbose_name='Для чего подходит'),
        ),
    ]
