# Generated by Django 6.0.5 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_templateusecase_templatedemo_use_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('contact', models.CharField(max_length=200, verbose_name='Контакт')),
                ('project_type', models.CharField(choices=[('website', 'Сайт'), ('bot', 'Telegram-бот'), ('webapp', 'Веб-приложение'), ('improvement', 'Доработка'), ('other', 'Другое')], max_length=30, verbose_name='Тип проекта')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='Предварительная стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('selected_options', models.TextField(blank=True, verbose_name='Выбранные опции')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('rejected', 'Отклонена')], default='new', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'заявка на проект',
                'verbose_name_plural': 'Заявки на проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
