# Generated by Django 6.0.5 on 2026-06-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projectorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Множитель цены')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'срок выполнения',
                'verbose_name_plural': 'Оформление заказа: сроки',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название группы')),
                ('input_type', models.CharField(choices=[('radio', 'Один вариант'), ('checkbox', 'Несколько вариантов')], default='checkbox', max_length=20, verbose_name='Тип выбора')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'группа опций заказа',
                'verbose_name_plural': 'Оформление заказа: группы опций',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Код')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='Базовая цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'тип проекта',
                'verbose_name_plural': 'Оформление заказа: типы проектов',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'условие работы',
                'verbose_name_plural': 'Оформление заказа: условия работы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбрано по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portfolio.orderoptiongroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'опция заказа',
                'verbose_name_plural': 'Оформление заказа: опции',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='orderoptiongroup',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='portfolio.orderprojecttype', verbose_name='Тип проекта'),
        ),
    ]
