# Generated by Django 6.0.5 on 2026-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_orderdeadline_orderoptiongroup_orderprojecttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Оплата по СБП', max_length=120, verbose_name='Заголовок')),
                ('bank_name', models.CharField(default='Альфа-Банк', max_length=120, verbose_name='Банк')),
                ('recipient_name', models.CharField(blank=True, max_length=160, verbose_name='Получатель')),
                ('phone_or_payment_info', models.CharField(blank=True, max_length=200, verbose_name='Телефон / реквизиты')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment/', verbose_name='QR-код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'настройки оплаты',
                'verbose_name_plural': 'Оформление заказа: оплата',
            },
        ),
        migrations.CreateModel(
            name='OrderBotGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Telegram-бот',
                'verbose_name_plural': 'Оформление заказа: Telegram-бот',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.orderoptiongroup',),
        ),
        migrations.CreateModel(
            name='OrderImprovementGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Доработка',
                'verbose_name_plural': 'Оформление заказа: Доработка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.orderoptiongroup',),
        ),
        migrations.CreateModel(
            name='OrderWebAppGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Веб-сервис',
                'verbose_name_plural': 'Оформление заказа: Веб-сервис',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.orderoptiongroup',),
        ),
        migrations.CreateModel(
            name='OrderWebsiteGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Оформление заказа: Сайт',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.orderoptiongroup',),
        ),
    ]
