# Generated by Django 6.0.5 on 2026-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('contact', models.CharField(max_length=160, verbose_name='Контакт')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'подтверждение оплаты',
                'verbose_name_plural': 'Подтверждения оплат',
                'ordering': ['-created_at'],
            },
        ),
    ]
