# Generated by Django 6.0.5 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_sitesettings_pwa_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_pwa_icon',
            field=models.ImageField(blank=True, null=True, upload_to='pwa/admin/', verbose_name='PWA-иконка админки'),
        ),
    ]
